name: fufis

channels:
   - conda-forge
   - bioconda

dependencies:
    - numpy==1.22.4
    - pandas==1.3.5
    - matplotlib==3.5.3
    - seaborn==0.13.2
    - matplotlib-venn==0.11.6
    - scipy==1.7.3
    - statsmodels==0.13.2
    - scikit-learn==1.0.2
    - networkx==2.5
    - adjusttext==1.3.0
    - colorcet==3.0.1
    - gprofiler-official==1.0.0
    - liftover==1.3.2
    - pybedtools==0.11.0
    - pybigwig==0.3.22
    - requests==2.32.0
    - upsetplot==0.9.0
    - deeptools==3.5.1
    - multiprocess==0.70.11.1
